// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukjobwlrxxbrzjeouozi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVram9id2xyeHhicnpqZW91b3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjI2MjYsImV4cCI6MjA2NTUzODYyNn0.6fQ0QweHriCYSqCmSAYiYnxuVCpIBBPggJOM-VyJ64s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);